use_default_settings: true

general:
  instance_name: 'searxng'

search:
  autocomplete: 'google'
  formats:
    - html
    - json

server:
  secret_key: 'REPLACE_WITH_SEARXNG_SECRET_AT_STARTUP' # Replaced at container startup by entrypoint.sh using SEARXNG_SECRET env var

engines:
  - name: wolframalpha
    disabled: false
